### ISSUE TITLE
textures

### ISSUE THREAD

**Issue by eristhea** [ix0rai/bodaciousberries#1]
tracking issue for textures
- [x] saskatoon bush stages 0-5
- [x] blackberry bush stages 0-4
- [x] raspberry bush stages 0-4
- [x] double saskatoon bush stages 0-3
- [x] strawberry bush stages 0-4
- [x] chorus berry bush stages 0-4
- [x] rainbowberry bush stages 0-4
- [x] lingonberry bush stages 0-4
- [x] gooseberry bush stages 0-3
- [x] grapes stages 0-3
- [x] goji berries stages 0-4

**Comment by Thonkman** [comment]
Closed because acai is acai
