### ISSUE TITLE
[bug] Latest Bodacious Berries Crashes Fabric

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [ix0rai/bodaciousberries#28]
**describe the bug**
Crashes on startup

**reproduction**
1. start launcher
2. Crashes

**version**
bodaciousberries-1.1.0+mc1.18.1.jar
[crash-2022-02-14_19.16.58-client.txt](https://github.com/ix0rai/bodaciousberries/files/8064846/crash-2022-02-14_19.16.58-client.txt)

**Comment by eristhea** [comment]
This issue doesn't exist on my end, but I *hope* I fixed it in my most recent commit
if [this version](https://modrinth.com/mod/berries/version/InFDpsbX) doesn't fix it, I'd really appreciate if you could narrow down whether or not this is a mod compatibility problem

**Comment by Cr4fTJuNkiE** [comment]
Okay. Will try it thanks.

**Comment by Cr4fTJuNkiE** [comment]
Yep! That fixed it. Thanks!

**Comment by eristhea** [comment]
anytime!
