### ISSUE TITLE
create over 10 unique berries

### ISSUE THREAD

**Issue by eristhea** [ix0rai/bodaciousberries#3]
there should be 10 or more unique types of berries for the initial release

- [x] saskatoon berries (initial commit)
- [x] raspberries (initial commit)
- [x] blackberries (initial commit)
- [x] strawberries (initial commit)
- [x] lingonberries (#10)
- [x] chorus berries (#8)
- [x] rainbowberries (#9)
- [x] goji berries (#12)
- [x] grapes (#11)
- [x] gooseberries (#13)

**Comment by Thonkman** [comment]
I removed the acai berries cause they're a whole other story
