### ISSUE TITLE
[bug] Crash Report - crash on drinking goji berry blend

### ISSUE THREAD

**Issue by Wpgradford** [ix0rai/bodaciousberries#40]
**describe the bug**
I drank a Goji Berry Blend and it crashed my game

**screenshots or logs**
Here's the crash log: [crash-2022-04-01_14.10.07-server.txt](https://github.com/ix0rai/bodaciousberries/files/8398047/crash-2022-04-01_14.10.07-server.txt)

**version**
Bodacious Berries 1.3.2+mc1.18.2

**Comment by eristhea** [comment]
I couldn't reproduce myself, but this should be fixed in [1.3.3](https://modrinth.com/mod/berries/version/1.3.3). Please test and tell me if it's still happening!

**Comment by Wpgradford** [comment]
I couldn't reproduce it either, I think you fixed it!
