### ISSUE TITLE
[bug] berry harvester has no specified tool

### ISSUE THREAD

**Issue by milkev** [ix0rai/bodaciousberries#42]
**describe the bug**
The berry harvester has no specified tool. This makes it extremely slow to mine, and it doesnt drop anything either. It should probably use a pickaxe or an axe.

**reproduction**
1. place berry harvester
2. attempt to mine it with pickaxe, axe, shovel, sword, etc...
3. mine it very slowly, and then recieve nothing when it does break

**version**
bodaciousberries-1.3.3+mc1.18.2

**Comment by milkev** [comment]
same applies for the juicer

**Comment by eristhea** [comment]
this issue has been fixed in version 1.4.0 which will be released today. The berry harvester is mined with an axe and the juicer is mined with a pickaxe. I've also added a particle texture to the juicer so that particles don't show up as missing textures when breaking. Thank you for reporting!
