### ISSUE TITLE
[bug] Grape Vines have no textures

### ISSUE THREAD

**Issue by Sunconure11** [ix0rai/bodaciousberries#44]
![image](https://user-images.githubusercontent.com/5614902/165762614-5e084a3e-74cf-491b-ae05-4646dce7d155.png)

**Comment by eristhea** [comment]
This was due to my usage of p03w's machete to optimise the jar, it seems to have broken the grapevine model JSON.
In the future, _please_ follow the issue templates to report bugs.

**Comment by eristhea** [comment]
Update: this is fixed on Machete's end, so it will be reintroduced in the next update.
