### ISSUE TITLE
[new feature] Add various forms of mod compat with common berries

### ISSUE THREAD

**Issue by Sunconure11** [ix0rai/bodaciousberries#45]
Stuff like strawberries, raspberries, blueberries, etc, are common in other mods. Would it be possible to add support for them if another mod is installed alongside them, for your recipes and such?

**Comment by eristhea** [comment]
Yes, it would actually be quite easy to implement this. It would be really helpful if you could help create a list of mods to add recipe compatibility with.

**Comment by eristhea** [comment]
Initial ideas:
- moreberries berries
- ecotones blueberries

**Comment by Sunconure11** [comment]
Alaska Native Craft has some berries... but I haven't found someone willing to fix the one final thing in it, the jigsaw structure for the fishing camp.

Witches Kitchen, when it releases, will have a few berries. But that will be a bit.

More Berries, while on the fantastical side of things, would be worth adding compat with

**Comment by Sunconure11** [comment]
One of the mods by Exline adds grapes

**Comment by Sunconure11** [comment]
Croptopia has a fuck ton of plants

**Comment by Sunconure11** [comment]
Promenade has blueberries

**Comment by melville-k** [comment]
@Sunconure11 calm down ! so much can be asked for at once !!

**Comment by eristhea** [comment]
ok so currently:
- ecotones (blueberries)
- exline's sandwich mod (grapes)
- croptopia (various)
- moreberries (all)
- promenade (blueberries again)
- alaska native craft (salmonberries/cloudberries)

**Comment by eristhea** [comment]
all those are currently recognised as berries as of my most recent change
next on the list is adding recipes for things like croptopia juice in the juicer

**Comment by eristhea** [comment]
@Sunconure11 unless you have any more suggestions I'll be releasing an update and closing this issue in a few days
