### ISSUE TITLE
[new feature] Add a config

### ISSUE THREAD

**Issue by Sunconure11** [ix0rai/bodaciousberries#46]
As far as I can tell, there is no config for the mod. The mod should have one to control the rates at which specific plants spawn

**Comment by eristhea** [comment]
I'm not sure how useful this will actually be, so I think this might wait until I move over Quilt, so I can use their config API instead of learning both Fabric's and Quilt's.
I'll leave the issue open, but give it low priority.

**Comment by eristhea** [comment]
due to having demand from a few people, this issue is being bumped up in priority!
a configurable version is up on the `next` branch and should be on modrinth and curseforge by the end of the week

**Comment by eristhea** [comment]
@Sunconure11 you can test the config on the `next` branch if you'd like to give feedback before it's released
