### ISSUE TITLE
[new feature] Mock Strawberries and Ground Cherries

### ISSUE THREAD

**Issue by Sunconure11** [ix0rai/bodaciousberries#48]
Two plants that could see some implementation in this mod, because well, this mod is about berries.

https://en.wikipedia.org/wiki/Potentilla_indica

https://en.wikipedia.org/wiki/Physalis

**Comment by eristhea** [comment]
mock strawberry -- no
ground cherry also feels a bit obscure, though the idea of cherries as in actual cherries is nice, I might do a nanking cherry-style bush in the future

**Comment by eristhea** [comment]
going to close this based on the obscurity of the things you're suggesting, but I'll make a new issue for plain vanilla cherries as they feel like a good fit for the mod.
