### ISSUE TITLE
[new feature] More foodstuffs based around the fruits of this mod

### ISSUE THREAD

**Issue by Sunconure11** [ix0rai/bodaciousberries#49]
You have quite a few berries, and yet aren't using them to their full potential.

**Comment by Thonkman** [comment]
that could happen, it'll probably end up being an extra branch tho. we'll see after we're done working on the new mod.

**Comment by eristhea** [comment]
I've made a decision that bodacious berries is going to stick with berries and drink forms of them (things like smoothies and jam will come in the future) but misc foodstuffs are not going to be implemented, sorry. If you want to make some yourself and submit a PR I'd be happy to rethink my opinion.
