### ISSUE TITLE
[bug] Missing translation for block.bodacious_berries.gooseberry_bush

### ISSUE THREAD

**Issue by andi-makes** [ix0rai/bodaciousberries#60]
**describe the bug**
The gooseberry bush block is the only bush without a translation.

**reproduction**
1. Look at gooseberry bush with something like wthit

**screenshots or logs**
![image](https://user-images.githubusercontent.com/26302678/193456316-3ef65fbe-361d-4e13-b101-b0d25273cc5b.png)

**version**
bodacious_berries-2.0.5-mc1.19.2

I really like your mod, thank you so much for your work!

**Comment by eristhea** [comment]
that's so odd, I'm surprised I forgot it.
thank you for your report and I'll get this fixed soon!

**Comment by eristhea** [comment]
fixed in my latest commit, the new version will likely release tomorrow.
