### ISSUE TITLE
[Bug] Lithium crashes with bodacious berries 2.0.7

### ISSUE THREAD

**Issue by StockiesLad** [ix0rai/bodaciousberries#62]
Lithium 0.10.3 got backported to 1.18.2, which means that the previous compat breaks it. Like the 1.19.2 version, it needs to be removed for it to work again.

**Comment by eristhea** [comment]
will be fixed today!

**Comment by StockiesLad** [comment]
Sounds good!

**Comment by eristhea** [comment]
fixed in 2.0.8!
having issues with my internet right now, so the only release is on modrinth. I'll get it out on github and curseforge later

**Comment by eristhea** [comment]
update: out on curseforge as well :)
