### ISSUE TITLE
No REI integration for harvester and juicer GUIs [bug] 

### ISSUE THREAD

**Issue by Wajiro** [ix0rai/bodaciousberries#64]
While the custom GUIs for berry harvester and juicer were compatible with REI in previous versions of the mod, they are not compatible now (the GUIs and the recipes are not shown in REI).
Weirdly enough, the toml config for this mod generates as an empty (0B) file.

Game Version: 1.19.2 [Fabric]
Fabric Loader: 0.14.11
Mod Version: 2.0.7

I don't think the log would be necessary, but I'll attach it if you ask.

**Comment by eristhea** [comment]
I removed it in favour of integrating with [EMI](https://modrinth.com/mod/emi), since the API is much cleaner and it's simpler to maintain for me as a developer.

If you insist on using REI, I could bring back support, but I only maintain 1.18.2 and 1.19.3 so you'd have to update your pack.
