### ISSUE TITLE
[bug] `nightconfig` dependency may cause crash

### ISSUE THREAD

**Issue by EightEggs** [ix0rai/bodaciousberries#68]
**describe the bug**

older version of `nightconfig` dependency may cause crash, see details below:

https://github.com/Fuzss/forgeconfigapiport/issues/65#issuecomment-2266716863

**version**

bodacious_berries-2.1.2-mc1.21

**Comment by eristhea** [comment]
this should be a pretty quick fix, i just have to make and apply some updates for my dependencies

**Comment by eristhea** [comment]
waiting on https://github.com/sisby-folk/kaleido-config/pull/6 to be merged, then this will be fixed!

**Comment by EightEggs** [comment]
> waiting on [sisby-folk/kaleido-config#6](https://github.com/sisby-folk/kaleido-config/pull/6) to be merged, then this will be fixed!

Thanks! i just love bodacious berries:)

**Comment by eristhea** [comment]
:heart:

**Comment by eristhea** [comment]
fixed in https://modrinth.com/mod/berries/version/2.1.3+mc1.21!
